[package]
name = "futures-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary = "1"
arbtest = "0.3"

[dev-dependencies]
tokio = { version = "1", features = ["sync"] }
diatomic-waker = "0.2"
scopeguard = "1"
futures = "0.3"
